#!/bin/bash

#PBS -l nodes=1:ppn=4
#SBATCH --mem=20G
#SBATCH --time=00:60:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_report
mkdir -p out_figs



singularity exec docker://brainlife/mne:1.2.1 python3 main.py


cat << EOF > product.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "Ica components",
         "base64": "$(base64 -w 0 out_figs/components_topo.png)"
       }
]
}
EOF
